---
default:
  image: registry.gitlab.com/media-cloud-ai/ci/rust:1.52.1-fix-tarpaulin-media

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  CONTAINER_IMAGE_NAME: media-cloud-ai/workers/media/rs_transcript_worker

stages:
    - test
    - publish

include: 
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-publish-docker.yml'
  - project: 'media-cloud-ai/ci/pipelines'
    file: '/rust/rust-base.yml'

...

